require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'quadrix' do
  config = use_native_modules!

  use_react_native!(:path => config[:reactNativePath])

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'

  target 'quadrixTests' do
    inherit! :complete
    # Pods for testing
  end
end
