# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:      
      - name: Clone repository
        uses: actions/checkout@v3
 
      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
 
      - name: Install dependencies
        run: npm install

      - name: Build web
        run: npm run build:web

      - name: Copy icon
        uses: canastro/copy-file-action@master
        with:
          source: "electron/resources/linux/icon.png"
          target: "electron/build-web/icon.png"

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Upload web
          path: electron/build-web

      - name: Change directory
        run: cd electron

      - name: Install dependencies
        run: npm install
     
      - name: Build snap amd64
        run: npm run build:snap

      - name: Build snap armhf
        run: npm run build:snap:armhf

      - name: Build deb amd64
        run: npm run build:deb

      - name: Build deb arm64
        uses: uraimo/run-on-arch-action@v2
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu_latest
          githubToken: ${{ github.token }}
          run: npm run build:deb

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Upload dist
          path: electron/dist
